/**
 * ChiroDX  --  CorelDraw Adapter Routes  v1.1
 * ─────────────────────────────────────────────
 * REST endpoints for the VBA ↔ Electron adapter.
 *
 * VBA (CorelDraw) calls:
 *   POST /corel/push                      — send selection payload
 *   GET  /corel/result/:sessionId         — poll for result
 *   POST /corel/result/:sessionId/applied — confirm apply
 *
 * Electron app calls:
 *   GET  /corel/selection                 — get latest selection
 *   GET  /corel/selection/:sessionId      — get specific session
 *   GET  /corel/sessions                  — list active sessions
 *   POST /corel/result                    — post processed result
 *   POST /corel/session/:sessionId/cancel — cancel session
 *
 * WebSocket at /corel/events is set up in server.js (needs the http.Server).
 */

import { Router } from 'express';
import {
  pushSession,
  getSession,
  getLatestSession,
  setResult,
  markApplied,
  cancelSession,
  listSessions,
  broadcast,
} from '../corel-state.js';
import { requireObject, requireString, ValidationError } from '../utils/validate.js';

const router = Router();

/**
 * Session IDs are generated by VBA as "s" + timestamp + random digits.
 * They end up in log lines and in Shape.Name, so keep them to a conservative
 * character set rather than accepting arbitrary strings.
 */
const SESSION_ID_PATTERN = /^[A-Za-z0-9_-]{1,64}$/;

/** Upper bound on shapes per push — a whole page of text, generously. */
const MAX_SHAPES = 500;

function readSessionId(raw, field = 'sessionId') {
  const value = requireString(raw, field, 64);
  if (!SESSION_ID_PATTERN.test(value)) {
    throw new ValidationError(`${field} contains invalid characters`);
  }
  return value;
}

function readShapes(raw, field = 'shapes') {
  if (raw === undefined || raw === null) return [];
  if (!Array.isArray(raw)) {
    throw new ValidationError(`${field} must be an array`);
  }
  if (raw.length > MAX_SHAPES) {
    throw new ValidationError(`${field} may contain at most ${MAX_SHAPES} entries`);
  }
  return raw;
}

// ── VBA → Server ─────────────────────────────────────────────

/**
 * POST /corel/push
 * VBA sends the serialized selection here.
 * Body: ShapeExchange JSON (see specs/shape-format.ts)
 */
router.post('/push', (req, res) => {
  const body = requireObject(req.body);
  const sessionId = readSessionId(body.sessionId);
  const shapes = readShapes(body.shapes);

  const payload = {
    sessionId,
    documentName: typeof body.documentName === 'string' ? body.documentName : '',
    pageNumber: Number.isFinite(body.pageNumber) ? body.pageNumber : 1,
    sentAt: typeof body.sentAt === 'string' ? body.sentAt : new Date().toISOString(),
    shapes,
  };

  const session = pushSession(payload);

  // Broadcast to all connected Electron clients
  broadcast({
    event: 'selection-changed',
    sessionId: session.sessionId,
    summary: {
      shapeCount: shapes.length,
      documentName: payload.documentName,
      pageNumber: payload.pageNumber,
    },
  });

  console.log(`[CorelAdapter] Push session=${sessionId} shapes=${shapes.length}`);
  res.json({ ok: true, sessionId: session.sessionId });
});

/**
 * GET /corel/result/:sessionId
 * VBA polls this to check whether Electron has posted a result.
 * Returns the full result payload when status === 'ready'.
 *
 * A missing session is reported with HTTP 200 and ok:false, because VBA polls
 * this in a loop and treats a non-200 as "server unreachable".
 */
router.get('/result/:sessionId', (req, res) => {
  const sessionId = readSessionId(req.params.sessionId);
  const session = getSession(sessionId);

  if (!session) {
    return res.json({ ok: false, status: '', error: 'Session not found or expired' });
  }

  if (session.status !== 'ready') {
    return res.json({ ok: true, status: session.status, shapes: [] });
  }

  res.json({
    ok: true,
    status: 'ready',
    sessionId: session.sessionId,
    shapes: session.result?.shapes ?? [],
  });
});

/**
 * POST /corel/result/:sessionId/applied
 * VBA calls this after successfully applying the result.
 */
router.post('/result/:sessionId/applied', (req, res) => {
  const sessionId = readSessionId(req.params.sessionId);
  const session = markApplied(sessionId);

  if (!session) {
    return res.status(404).json({ ok: false, error: 'Session not found' });
  }

  broadcast({ event: 'result-applied', sessionId: session.sessionId });
  console.log(`[CorelAdapter] Applied session=${session.sessionId}`);

  res.json({ ok: true });
});

// ── Electron → Server ─────────────────────────────────────────

/**
 * GET /corel/selection
 * Electron app gets the most recent selection.
 */
router.get('/selection', (req, res) => {
  const session = getLatestSession();
  if (!session) {
    return res.json({ ok: true, session: null });
  }
  res.json({ ok: true, session: sessionSummary(session) });
});

/**
 * GET /corel/selection/:sessionId
 * Electron app gets a specific session with full payload.
 */
router.get('/selection/:sessionId', (req, res) => {
  const sessionId = readSessionId(req.params.sessionId);
  const session = getSession(sessionId);

  if (!session) {
    return res.status(404).json({ ok: false, error: 'Session not found or expired' });
  }

  res.json({
    ok: true,
    session: { ...sessionSummary(session), payload: session.payload },
  });
});

/**
 * GET /corel/sessions
 * Electron app lists all pending/ready sessions.
 */
router.get('/sessions', (req, res) => {
  res.json({ ok: true, sessions: listSessions().map(sessionSummary) });
});

/**
 * POST /corel/result
 * Electron app posts the processed result.
 * Body: { sessionId, shapes: ShapeData[] }
 * (Only shapes that changed need to be included)
 */
router.post('/result', (req, res) => {
  const body = requireObject(req.body);
  const sessionId = readSessionId(body.sessionId);
  const shapes = readShapes(body.shapes);

  const session = getSession(sessionId);
  if (!session) {
    return res.status(404).json({ ok: false, error: 'Session not found or expired' });
  }

  setResult(sessionId, { sessionId, shapes });

  broadcast({ event: 'result-ready', sessionId });
  console.log(`[CorelAdapter] Result ready session=${sessionId} shapes=${shapes.length}`);

  res.json({ ok: true, sessionId });
});

/**
 * POST /corel/session/:sessionId/cancel
 * Electron app cancels a session (user dismissed it).
 */
router.post('/session/:sessionId/cancel', (req, res) => {
  const sessionId = readSessionId(req.params.sessionId);
  const session = cancelSession(sessionId);

  if (!session) {
    return res.status(404).json({ ok: false, error: 'Session not found' });
  }

  broadcast({ event: 'session-expired', sessionId: session.sessionId });
  res.json({ ok: true });
});

// ── Helpers ───────────────────────────────────────────────────

function sessionSummary(session) {
  return {
    sessionId:    session.sessionId,
    status:       session.status,
    shapeCount:   session.payload?.shapes?.length ?? 0,
    documentName: session.payload?.documentName ?? '',
    pageNumber:   session.payload?.pageNumber ?? 1,
    sentAt:       session.payload?.sentAt ?? '',
    createdAt:    session.createdAt,
    updatedAt:    session.updatedAt,
  };
}

export default router;
